const data = {
  products: [
    {
      name: "تی شرت جوتی  مردانه برند پی لس ",
      slug: "free-shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 70000,
      brand: "Brand Payless",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: " برند پی لس پیراهن مردانه جوتی جینز",
      slug: "fit-shirt",
      category: "Shirts",
      image: "/images/shirt2.jpg",
      price: 220000,
      brand: "JootiJeans",
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "پولوشرت مردانه جوتی جینز",
      slug: "slim-shirt",
      category: "Shirts",
      image: "/images/shirt3.jpg",
      price: 339000,
      brand: "Raymond",
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "شلوار جین مردانه جوتی جینز",
      slug: "golf-pants",
      category: "Pants",
      image: "/images/pants1.jpg",
      price: 1279000,
      brand: "Oliver",
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: "Smart looking pants",
    },
    {
      name: "شلوار کتان مردانه جوتی جینز",
      slug: "fit-pants",
      category: "Pants",
      image: "/images/pants2.jpg",
      price: 1179000,
      brand: "Zara",
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "شلوار برند پی لس مردانه برند پی لس ",
      slug: "classic-pants",
      category: "Pants",
      image: "/images/pants3.jpg",
      price: 75000,
      brand: "Casely",
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: "A popular pants",
    },
  ],
};

export default data;
